variable "instance_ami" {}
variable "instance_type" {}
variable "instance_key_pair" {}
variable "instance_subnet" {}
variable "instance_associate_public_ip_address" {}
variable "instance_security_group" {}
variable "instance_profile" {}
variable "instance_monitoring" {}
variable "instance_disable_api_termination" {}
variable "instance_user_data" {}
variable "instance_tag_name" {}
variable "instance_tag_description" {}
variable "instance_tag_project" {}
variable "instance_tag_environment" {}
