variable "das_ami" {}
variable "das_instance_type" {}
variable "das_key_pair" {}
variable "das_subnet" {}
variable "das_private_ip" {}
variable "das_security_group" {}
variable "das_tag_name" {}
variable "das_tag_description" {}
variable "das_tag_project" {}
variable "das_tag_environment" {}
variable "das_dc_dns" {}
