variable "tropics_ami" {}
variable "tropics_instance_type" {}
variable "tropics_key_pair" {}
variable "tropics_subnet" {}
variable "tropics_security_group" {}
variable "tropics_tag_name" {}
variable "tropics_tag_description" {}
variable "tropics_tag_project" {}
variable "tropics_tag_environment" {}
variable "tropics_dc_dns" {}
