#!/bin/bash
yum install -y keepalived
cat <<KEEPALIVED_CONF > /etc/nginx/nginx.conf
user  nginx;
worker_processes  2;
error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;
events {
    worker_connections 512;
}
http {
    include         /etc/nginx/mime.types;
    default_type    application/octet-stream;
    access_log  /var/log/nginx/access.log  combined:
    error_log  /var/log/nginx/error.log  error;
    server {
        listen 80 default_server;
        proxy_pass      ${dc_dns};
    }
}
KEEPALIVED_CONF
