variable "https_elb_subnets" {}
variable "https_elb_cross_zone" {}
variable "https_elb_idle_timeout" {}
variable "https_elb_connection_draining" {}
variable "https_elb_connection_draining_timeout" {}
variable "https_elb_security_groups" {}
variable "https_elb_ssl_cert_arn" {}
variable "https_elb_instances" {}
variable "https_elb_instance_port" {}
variable "https_elb_instance_protocol" {}
variable "https_elb_healthy_threshold" {}
variable "https_elb_unhealthy_threshold" {}
variable "https_elb_health_check_timeout" {}
variable "https_elb_health_check_target_path" {}
variable "https_elb_health_check_interval" {}
variable "https_elb_tag_name" {}
variable "https_elb_tag_description" {}
variable "https_elb_tag_project" {}
variable "https_elb_tag_environment" {}
