variable "ldaps_ami" {}
variable "ldaps_instance_type" {}
variable "ldaps_key_pair" {}
variable "ldaps_subnet" {}
variable "ldaps_security_group" {}
variable "ldaps_tag_name" {}
variable "ldaps_tag_description" {}
variable "ldaps_tag_project" {}
variable "ldaps_tag_environment" {}
variable "ldaps_dc_dns" {}
